### PR TITLE
Feature: add "month" parameter to set the default displayed month

### PR DESCRIPTION
**Pull request by Fe4nn0r**
Even if the parameter is not defined, the default will be today, as defined in the `link` function:
`scope.month = scope.month || moment().startOf('day');`

### CODE REVIEW

**Comment by mgohin** [comment]
It was working event without this add, but it's better with it, thx ;)

**Comment by Fe4nn0r** [comment]
Hello, thank you very much for the quick responde and merge :)
I didn't manage to make it work without this attribute, isn't the directive scope isolated from the controller scope ?
(it may be dependant on the angular version though)

Could you please drop a new tag for it ?
Thanks again !

**Comment by mgohin** [comment]
Yep but you just pass it to the directive

Controller :

    $scope.myMonth = moment(TIMESTAMP);


HTML

    <multiple-date-picker month="myMonth" />

Isn't this working ? Maybe I'm wrong, it's been a few month I didn't code with Angular :p

**Comment by Fe4nn0r** [comment]
Yep, but afaik it works only when the attribute you want to pass to the scope is defined in the directive :)

**Comment by mgohin** [comment]
Ok, I'll go to bed less stupid tonight ! Thx ;)

**Pull request merged**
