### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Xal3ph**
Added calendar-mode to toggle month picker as well as day picker.

### CODE REVIEW

**Comment by Xal3ph** [comment]
Let me know if there is anything I can do to help make this pull request easier (if possible).

**Comment by mgohin** [comment]
Nice, I'm just wondering if we should create a real fork and use it only as MultipleMonthPicker because there are several options available for date picking that we can't use for month picking right now.
I think it would be better to have 2 directives, one for dates as mine and one for month.
If you agree you can create a fork of MultipleDatePicker, change everything to fit month picking only and I'll add a link in the readme to your fork.

**Comment by Xal3ph** [comment]
So you're thinking something like MultipleMonthPicker and MultipleDatePicker?

**Comment by mgohin** [comment]
Yes

**Comment by Xal3ph** [comment]
Alright - I'm closing.

**Comment by Xal3ph** [comment]
Updated and put on https://github.com/Xal3ph/MultipleMonthPicker  Also published to bower

**Pull request closed without merging**
