### PR TITLE
add past and future classes

### PR DESCRIPTION
**Pull request by jdeniau**
Thank you

### CODE REVIEW

**Comment by mgohin** [comment]
Thx ;)

**Comment by jdeniau** [comment]
Well that was quick ! :D

Can you drop a new tag for it ?

**Comment by mgohin** [comment]
Hehe, was doing it ;)
https://github.com/arca-computing/MultipleDatePicker/releases/tag/1.2.1

**Comment by jdeniau** [comment]
great ! thank you !

**Comment by mgohin** [comment]
I'm adding it to https://github.com/arca-computing/MultipleDatePickerReact too, thx ;)

**Pull request merged**
